### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [njdom24/Damino-Zsh-Theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by njdom24** [comment]
Thanks for the pointer! I'm new to the community so this is a great help!

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/776
